extends: common.yaml

data:
  prepared_path: /scratch/wangpc/B-Spline-Inpainting/robot_policy/outputs/BSP_UNET_V4_HANGING_MUG_600E/cache/prepared/bspline
  action_representation: bspline
  observation_horizon: 2

policy:
  architecture: bsp_unet_fm

wandb:
  run_suffix: v4-hanging-mug-bspline-h2-batch64-600epochs
