extends: common.yaml
data:
  prepared_path: /scratch/wangpc/B-Spline-Inpainting/robot_policy/outputs/FULL_VISION_512/cache/bspline
  action_representation: bspline
  observation_horizon: 1
policy:
  architecture: bsp_unet_discrete
  discrete_full_mask_probability: 0.5
train:
  updates: 10000
  min_lr_ratio: 1.0
wandb:
  run_suffix: discrete-bspline-1frame-fullmask50-fullval
