extends: common.yaml
data:
  prepared_path: /scratch/wangpc/B-Spline-Inpainting/robot_policy/outputs/BSP_UNET_V3/cache/prepared/raw
  action_representation: raw
  observation_horizon: 1
policy:
  architecture: bsp_unet_fm
wandb:
  run_suffix: fm-raw-1frame
